### ISSUE TITLE
"Setup Development Database" link in README doesn't work

### ISSUE THREAD

**Issue by okeefm** [synthetichealth/gofhir#17]
The "Setup Development Database" link in [this section](https://github.com/synthetichealth/gofhir#running-the-server-locally) of the README, which is https://github.com/synthetichealth/gofhir/blob/ptstats/postgres/postgres-setup.md#setup-development-database , 404s when you click on it.

**Comment by okeefm** [comment]
Additionally, most of the links in the [Building the Server Locally](https://github.com/synthetichealth/gofhir#building-the-server-locally) section point to `IE`'s docs, not `synthetichealth`'s, and the one that does point to `synthetichealth`'s ([Install Postgres and Extensions](https://github.com/synthetichealth/gofhir/blob/master/docs/postgres-setup.md#install-postgres)) 404s as well.

**Comment by cjduffett** [comment]
The Postgres database is no longer needed to test/run the GoFHIR server. Removed that artifact from the README. Since the intervention-engine/fhir repository is a _library_, not a standalone server the GoFHIR server is an example of _using_ that library. Naturally most of the documentation for using that library is in the intervention-engine repo.
